# Dockerfile for Worker Service
FROM node:18-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY apps/worker-service ./apps/worker-service
COPY libs ./libs

RUN npm install

RUN npm run build -w worker-service

CMD ["node", "dist/apps/worker-service/main.js"]
