# Dockerfile for Simulator service
FROM node:18-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY apps/simulator ./apps/simulator
COPY libs ./libs

RUN npm install

RUN npm run build -w simulator

CMD ["node", "dist/apps/simulator/main.js"]
